name: Update Google Sheet with Current Time
on:
  schedule:
    - cron: '*/1 * * * *'  # Run every minute
jobs:
  update-time:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install  # Installs dependencies from package.json
      - name: Run script
        env:
          GOOGLE_SHEETS_CLIENT_EMAIL: ${{ secrets.GOOGLE_SHEETS_CLIENT_EMAIL }}
          GOOGLE_SHEETS_PRIVATE_KEY: ${{ secrets.GOOGLE_SHEETS_PRIVATE_KEY }}
        run: npm start  # Runs node script.js