name: 3.Instruments to JSON
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Daily at midnight UTC (~5:30 AM IST)
permissions:
  contents: write # Required to commit and push
jobs:
  save-instruments:
    runs-on: ubuntu-latest
    environment: gmail # Access GMAIL and PRIVATE_KEY
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }} # Use PAT_TOKEN for checkout
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Dependencies
        run: npm install
      - name: Run script to save instruments
        env:
          GMAIL: ${{ secrets.GMAIL }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          node lib/tokendone.js
          ls -la # List files to confirm instruments.json
      - name: Commit and push instruments.json
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git status
          git add instruments.json
          git diff --staged
          git commit -m "Update instruments.json with latest scrip data" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}